import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";
import { api } from "~/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen gap-10 flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <strong className="text-secondary">Pee Pee Poo Poo</strong>
        <Button onClick={()=>alert('Pee Pee')}>Pee Pee</Button>
        <Button onClick={()=>alert('Poo Poo')}>Poo Poo</Button>
      </main>
    </>
  );
}

